### ISSUE TITLE
Bash completion should be opt-in

### ISSUE THREAD

**Issue by andrey-zherikov** [BradleyChatha/jcli#31]
There are few issues I observe with this feature:
- Users not always need bash completion. For example, target system doesn't have it (e.g. Windows).
- Current implementation call the tool itself and this might have unexpected side effects. For example, initialization code (that runs before `main`) might do I/O.
- Command line is force-populated with some internal commands that is out of user's control.

Also there might be a use case when user wants to structure the code in a way where the tool and bash-completion parts are separated into two different executables, for example `mytool` and `mytool_bash_completion`. The latter might be used to generate bash completion script as a separate build step.

**Comment by BradleyChatha** [comment]
> Users not always need bash completion. For example, target system doesn't have it (e.g. Windows).

I'm aware of, but in cases like that the completion commands simply never gets used anyway. The runtime overhead is a delegate being allocated and an append to an array per command, which I'd argue isn't a priority to address at the moment.

> Current implementation call the tool itself and this might have unexpected side effects. For example, initialization code (that runs before main) might do I/O.

I've been thinking about this as well, even for programs that *want* to use bash completion. A naive solution would be to add a helper function such as `bool bashCompletionRequested(string[] args)` so that the user's main function can bypass pointless setup code.

It's also worth noting commands and services are only constructed on-use, so command ctor code shouldn't ever be called when the tool is used for completion.

Another reason is I barely know bash, and wasn't willing to start *bash*ing my head against a wall trying to generate a full bash script from the data JCLI has, when I could instead just program the tool to do it for you.

e.g. If your main function looked a little like this:

```d
void main(string[] args)
{
    auto services = ...; // Services aren't constructed until they're used, so any I/O code again, won't be called on a bash completion use path.
    auto cli = new CommandLineInterface...;

    if(args.bashCompletionRequested())
    {
        // Allow JCLI to handle things from here.
        return cli.parseAndExecute(...);
    }

    // Some I/O and side affect operations
    ...

   return cli.parseAndExecute();
}
```

Then there shouldn't be any side effects, since no user-defined code should actually be called (services won't be constructed, commands won't be constructed, no biniding occurs so `@ArgBinderFunc` and `@ArgValidator` are never used, etc.).

It's a bit of a bandaid though.

> Command line is force-populated with some internal commands that is out of user's control.

These commands are prefixed with "__jcli:", which I very much doubt a user would ever want to use.

For the current two commands there shouldn't be much of an issue, since the bash completion is completely internal to CommandLineInterface anyway.

Depending on whether there's more internal commands in the future, I might agree with you that there's an issue there.

> Also there might be a use case when user wants to structure the code in a way where the tool and bash-completion parts are separated into two different executables, for example mytool and mytool_bash_completion. The latter might be used to generate bash completion script as a separate build step.

I'm not overly sure what JCLI can do to help support that use case.

You'd either need to duplicate all the JCLI-relevant parts over to the bash_completion tool (All the `@Comand`, `@CommandPositionalArg`, etc. marked things) so that JCLI knows how to get that information.

Or you'd need a seperate project containing all the commands, that mytool and mytool_bash_completion share, so again JCLI knows what information it's dealing with.

Or you could just build mytool first, then call the appropriate internal command for the script afterwards.

Finally, this is yet another configurable thing for the user, so I've opened #32 to discuss on how best to handle configuration of `CommandLineInterface`.

**Comment by andrey-zherikov** [comment]
One more issue with bash completion `jcli` - it requires `-J` option.
```bash
$ dmd -i -I../../../AppData/Local/dub/packages/jioc-0.2.0/jioc/source/ -Isource -Iexamples/00-basic-usage-default-command/source -run examples/00-basic-usage-default-command/source/app.d
source\jaster\cli\core.d(736): Error: need `-J` switch to import text file `bash_completion.sh`
examples\00-basic-usage-default-command\source\app.d(14): Error: template instance `jaster.cli.core.CommandLineInterface!(commands)` error instantiating
```

You didn't the point about side-effect. Consider user's code that does something in module static initializers. this code will be executed every time when bash completion is invoked:
```d
static this()
{
// do some stuff here, like 3rd-party library initialization or reading config file
}
void main(string[] args)
{
    auto cli = new CommandLineInterface...;
    ...
   return cli.parseAndExecute();
}
```


> > Command line is force-populated with some internal commands that is out of user's control.
> 
> These commands are prefixed with "__jcli:", which I very much doubt a user would ever want to use.
> 
> For the current two commands there shouldn't be much of an issue, since the bash completion is completely internal to CommandLineInterface anyway.

I agree that overhead is small but consider an user who doesn't want bash completion at all. How can one do that?

> > Also there might be a use case when user wants to structure the code in a way where the tool and bash-completion parts are separated into two different executables, for example mytool and mytool_bash_completion. The latter might be used to generate bash completion script as a separate build step.
> 
> I'm not overly sure what JCLI can do to help support that use case.
> 
> You'd either need to duplicate all the JCLI-relevant parts over to the bash_completion tool (All the `@Comand`, `@CommandPositionalArg`, etc. marked things) so that JCLI knows how to get that information.
> 
> Or you'd need a seperate project containing all the commands, that mytool and mytool_bash_completion share, so again JCLI knows what information it's dealing with.

It's much easier than you think. Just put CLI-related things into separate module (both `bash_completion.d` and `main.d` import `cli.d`):
```
mytool/bash_completion.d
mytool/cli.d
mytool/main.d
```

> Finally, this is yet another configurable thing for the user, so I've opened #32 to discuss on how best to handle configuration of CommandLineInterface.

I disagree that this is configuration. It should be done through different API, like (I don't like how this looks but you should get an idea):
```d
//main.d
void main(string[] args)
{
    import mytool.cli;
    auto cli = new CommandLineInterface!(mytool.cli);
    return cli.parseAndExecute();
}

//bash_completion.d
void main(string[] args)
{
    import mytool.cli;
    auto cli = new CommandLineInterface!(mytool.cli);
    return cli.bashCompletion();
}
```
